package session_08;

import org.testng.annotations.Test;

import io.restassured.RestAssured;
import io.restassured.response.Response;
import io.restassured.specification.RequestSpecification;

public class ApiKey {
	
	
	// https://api.openweathermap.org/data/2.5/weather?q={city name}&appid={API key}
	
	/* API keys are unique strings characters that are used to authenticate users and allow them to access the API. 
	 * The Key is generated by the server and provided to the client.
	 * The client then sends the key along with each request to the server, and the server uses it to identify the user and authorize the 
	 * access to the resources
	 */
	
	@Test
	
	public void APIKEYTOKEN() {
		
		RequestSpecification reqSpc = RestAssured.given();
		reqSpc.baseUri("https://api.openweathermap.org");
		reqSpc.basePath("/data/2.5/weather");
		reqSpc.queryParam("q", "delhi").queryParam("appid", "296560aa9261b169906dac01a0234a83");
		
		Response resp = reqSpc.get();
		
				
		System.out.println("Status line message is :"+resp.statusLine());
		System.out.println("Status body message is :"+resp.body().asString());
		
	}
}
